### ISSUE TITLE
assert $schema in data error

### ISSUE THREAD

**Issue by jmartinm** [inspirehep/inspire-next#1307]
We currently get in the first page of search results on QA, the error:

``` 
Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/opt/inspire/lib/python2.7/site-packages/flask_cors/extension.py", line 188, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1625, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/inspire/lib/python2.7/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_rest/views.py", line 207, in dispatch_request
    *args, **kwargs
  File "/opt/inspire/lib/python2.7/site-packages/flask/views.py", line 149, in dispatch_request
    return meth(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_records_rest/views.py", line 444, in get
    item_links_factory=self.item_links_factory,
  File "/opt/inspire/lib/python2.7/site-packages/invenio_rest/views.py", line 188, in make_response
    return serializer(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_records_rest/serializers/response.py", line 70, in view
    item_links_factory=item_links_factory),
  File "/opt/inspire/lib/python2.7/site-packages/invenio_records_rest/serializers/json.py", line 88, in serialize_search
    ) for hit in search_result['hits']['hits']],
  File "/opt/inspire/src/inspire/inspirehep/modules/pidstore/fetchers.py", line 38, in inspire_recid_fetcher
    assert "$schema" in data
```

So it seems that some records might be getting loaded without `$schema` on them. Have not seen this error before, needs to be checked.

**Comment by david-caro** [comment]
There's only one record that has the issue, and it's http://inspirehep.net/record/1441165, in json form:

```
{u'abstracts': [{u'source': u'APS',
                 u'value': u'By lowering their energy threshold, direct dark matter searches can reach the neutrino floor with experimental technology that is now in development. The <math><mrow><mmultiscripts><mrow><mi>Be</mi></mrow><mprescripts></mprescripts><none></none><mrow><mn>7</mn></mrow></mmultiscripts></mrow></math> flux can be detected with <math><mo>\u223c</mo><mn>10</mn><mtext>\u2009</mtext><mtext>\u2009</mtext><mi>eV</mi></math> nuclear recoil energy threshold and 50\xa0kg/yr exposure. The <math><mi>p</mi><mi>e</mi><mi>p</mi></math> flux can be detected with <math><mo>\u223c</mo><mn>3</mn></math> ton/yr exposure, and the first detection of the CNO flux is possible with similar exposure. The <math><mi>p</mi><mi>p</mi></math> flux can be detected with threshold of <math><mo>\u223c</mo><mi>eV</mi></math> and only <math><mrow><mo>\u223c</mo><mtext>\u2009</mtext><mtext>\u2009</mtext><mi>kg</mi><mo>/</mo><mi>yr</mi></mrow></math> exposure. These can be the first pure neutral current measurements of the low-energy solar neutrino flux. Measuring this flux is important for low mass dark matter searches and for understanding the solar interior.'}],
 u'authors': [{u'affiliations': [{u'value': u'Mitchell Institute for Fundamental Physics and Astronomy, Department of Physics and Astronomy, Texas A&M University, College Station, Texas 77845, USA'}],
               u'full_name': u'Strigari, Louis E.',
               u'given_names': u'Louis E.',
               u'raw_name': u'Louis E. Strigari',
               u'signature_block': u'STRAGARl',
               u'surname': u'Strigari',
               u'uuid': u'65b1090a-17f0-449a-adc0-6222b66c02b7'}],
 u'collections': [{u'primary': u'HEP'},
                  {u'primary': u'Citeable'},
                  {u'primary': u'Published'}],
 u'copyright': [{u'holder': u'American Physical Society',
                 u'material': u'Article',
                 u'statement': u'\xa9 2016 American Physical Society',
                 u'year': u'2016'}],
 u'dois': [{u'value': u'10.1103/PhysRevD.93.103534'}],
 u'earliest_date': u'2016-05-26',
 u'imprints': [{u'date': u'2016-05-26'}],
 u'license': [{u'license': u'',
               u'material': u'',
               u'url': u'http://link.aps.org/licenses/aps-default-license'}],
 u'page_nr': u'5',
 u'publication_info': [{u'journal_issue': u'10',
                        u'journal_title': u'Phys. Rev. D',
                        u'journal_volume': u'93',
                        u'note': u'',
                        u'page_artid': u'',
                        u'pubinfo_freetext': u'',
                        u'year': u'2016'}],
 u'subject_terms': [],
 u'titles': [{u'source': u'APS',
              u'subtitle': u'',
              u'title': u'Neutrino floor at ultralow threshold'}]}
```

**Comment by jacquerie** [comment]
It appears that now that record has a `$schema`: https://qa.inspirehep.net/api/literature/1441165. Time to close this issue?

**Comment by jacquerie** [comment]
Sentry: https://sentry.cern.ch/inspire-sentry/inspire-labs-qa/group/602741/

**Comment by jmartinm** [comment]
This issue did not appear again right? Have not seen it on `nightly`. Shall we close?

**Comment by kaplun** [comment]
:+1:
