### ISSUE TITLE
Article Workflow: UnmappedInstanceError on delete_self_and_stop_processing task

### ISSUE THREAD

**Issue by mihaibivol** [inspirehep/inspire-next#1341]
Way to reproduce:
- Fire up `scrapyd` and `scrapyd-deploy`
- Run `inspirehep oaiharvester harvest -m arXiv -u http://export.arxiv.org/oai2 -f 2016-06-24 -t 2016-06-26 -s 'physics:hep-th' -a 'spider=arXiv' -a 'workflow=article'
  `
- Wait for ~37 records to be halted
- Run `inspirehep oaiharvester harvest -m arXiv -u http://export.arxiv.org/oai2 -f 2016-06-24 -t 2016-06-26 -s 'physics:hep-th' -a 'spider=arXiv' -a 'workflow=article'` again
- Now if duplicate records are both in `holdingpen` and in the initial harvesting state this error happens

```
Traceback (most recent call last):
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 529, in _process
    self.run_callbacks(callbacks, objects, obj)
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 481, in run_callbacks
    self.execute_callback(callback_func, obj)
  File "/virtualenv/lib/python2.7/site-packages/workflow/engine.py", line 564, in execute_callback
    callback(obj, self)
  File "/code/inspirehep/modules/workflows/tasks/matching.py", line 278, in delete_self_and_stop_processing
    db.session.delete(obj)
  File "/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/virtualenv/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 1644, in delete
    raise exc.UnmappedInstanceError(instance)
UnmappedInstanceError: Class 'invenio_workflows_files.api.WorkflowObject' is not mapped
```

EDIT 1

The error comes from here https://github.com/inspirehep/inspire-next/blob/ae2c03af6fe1f51226913dcfa1fca3d753a6ee92/inspirehep/modules/workflows/tasks/matching.py#L278

`obj` is not a Model

EDIT 2

The fix would be to get the `WorkflowObjectModel` associated with the `WorkflowObject` and remove that instead.

**Comment by mihaibivol** [comment]
The question label is there if the bug can be reproduced by somebody else :)

**Comment by jacquerie** [comment]
> UnmappedInstanceError: Class 'invenio_workflows_files.api.WorkflowObject' is not mapped

This makes sense: a `WorkflowObject` is not a model, so why should it be mapped? I believe this call is erroneous: https://github.com/inspirehep/inspire-next/blob/ae2c03af6fe1f51226913dcfa1fca3d753a6ee92/inspirehep/modules/workflows/tasks/matching.py#L278

**Comment by mihaibivol** [comment]
@jacquerie yup. But isn't `obj` sometimes a `Record` in other tasks?

**Comment by jacquerie** [comment]
>  But isn't `obj` sometimes a `Record` in other tasks?

AFAIK, this is never the case.

**Comment by david-caro** [comment]
I agree with @jacquerie, I think there should be an interface declared, something like `Workflow` that defines the `delete` method, maybe leave this by default but allow to override it, so you can write your own delete functionality (not everyone needs a model, or maybe something more complex is needed...).

In any case, the above opinion does not have the whole context of why that was done like that on the first place, so there might be another reasons.

I'll try to write the minimal interface and adapt the current code to override that delete method on inspire side.

**Comment by david-caro** [comment]
Hmm... that is actually done on inspire side all of it xd, got confused.
