### ISSUE TITLE
workflows: one_or_none error

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2362]
We are seeing this issue in production for some workflows...

```
[2017-05-19 18:35:06,725: WARNING/Worker-4] [2017-05-19 18:35:06,724] ERROR in engine: Error:
Traceback (most recent call last):
  File "/opt/inspire/src/workflow/workflow/engine.py", line 529, in _process
    self.run_callbacks(callbacks, objects, obj)
  File "/opt/inspire/src/workflow/workflow/engine.py", line 454, in run_callbacks
    indent + 1)
  File "/opt/inspire/src/workflow/workflow/engine.py", line 454, in run_callbacks
    indent + 1)
  File "/opt/inspire/src/workflow/workflow/engine.py", line 481, in run_callbacks
    self.execute_callback(callback_func, obj)
  File "/opt/inspire/src/workflow/workflow/engine.py", line 564, in execute_callback
    callback(obj, self)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/utils.py", line 136, in _decorator
    res = func(*args, **kwargs)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/tasks/arxiv.py", line 70, in arxiv_fulltext_download
    url=current_app.config['ARXIV_PDF_URL'].format(arxiv_id=arxiv_id),
  File "/opt/inspire/lib/python2.7/site-packages/backoff/_sync.py", line 85, in retry
    ret = target(*args, **kwargs)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/utils.py", line 178, in download_file_to_workflow
    return workflow.files[name]
  File "/opt/inspire/lib/python2.7/site-packages/invenio_records_files/api.py", line 161, in __getitem__
    obj = ObjectVersion.get(self.bucket, key)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_files_rest/models.py", line 1048, in get
    return cls.query.filter(*filters).one_or_none()
  File "/opt/inspire/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2698, in one_or_none
    "Multiple rows were found for one_or_none()")
MultipleResultsFound: Multiple rows were found for one_or_none()
```

**Comment by jacquerie** [comment]
This was happening when we retried the download step of workflows without taking care of deleting previously added rows in the files metadata table. It should no longer be happening.
