### ISSUE TITLE
scripts: recreate_records only works once

### ISSUE THREAD

**Issue by jacquerie** [inspirehep/inspire-next#2393]
## Expected Behavior
I should be able to use `scripts/recreate_records` as many times as I want.

## Current Behavior
The second time `scripts/recreate_records` is run, it fails when populating the DB fixtures because the fixtures of the first invocation are still there, so a uniqueness constraint is violated.

## Steps to Reproduce
1. Start from a fresh install.
2. Run `scripts/recreate_records`.
3. Run `scripts/recreate_records`.

It looks like some tables are not dropped by `inspirehep db drop --yes-i-know` at the beginning of the second invocation. This wasn't happening before, and might be caused by some upstream changes in the entry points or something like that.

**Comment by jacquerie** [comment]
BTW my ugly workaround at the moment is to destroy and recreate the DB from `psql` as described in https://github.com/inspirehep/inspire-next/blob/f2e42539c409f9ece36338bb5df03ba47437d7a1/INSTALL.rst#create-database.

**Comment by jacquerie** [comment]
Stacktrace:

```python
Traceback (most recent call last):
  File "/home/skaplun/.virtualenvs/labs3/bin/inspirehep", line 11, in <module>
    load_entry_point('Inspirehep', 'console_scripts', 'inspirehep')()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/flask/cli.py", line 380, in main
    return AppGroup.main(self, *args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/flask/cli.py", line 257, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/src/inspire-next/inspirehep/modules/fixtures/cli.py", line 45, in init
    init_all_storage_paths()
  File "/home/skaplun/.virtualenvs/labs3/src/inspire-next/inspirehep/modules/fixtures/files.py", line 76, in init_all_storage_paths
    init_default_storage_path()
  File "/home/skaplun/.virtualenvs/labs3/src/inspire-next/inspirehep/modules/fixtures/files.py", line 48, in init_default_storage_path
    db.session.commit()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/scoping.py", line 157, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 864, in commit
    self.transaction.commit()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 455, in commit
    self._prepare_impl()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 435, in _prepare_impl
    self.session.flush()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2080, in flush
    self._flush(objects)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2198, in _flush
    transaction.rollback(_capture_exception=True)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/util/langhelpers.py", line 60, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/session.py", line 2162, in _flush
    flush_context.execute()
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 373, in execute
    rec.execute(self)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py", line 532, in execute
    uow
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 178, in save_obj
    mapper, table, insert)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/orm/persistence.py", line 804, in _emit_insert_statements
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
    return meth(self, multiparams, params)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
    compiled_sql, distilled_params
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
    context)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
    exc_info
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "uq_files_location_name"
DETAIL:  Key (name)=(default) already exists.
 [SQL: 'INSERT INTO files_location (created, updated, name, uri, "default") VALUES (%(created)s, %(updated)s, %(name)s, %(uri)s, %(default)s) RETURNING files_location.id'] [parameters: {'default': True, 'updated': datetime.datetime(2017, 6, 2, 7, 30, 6, 84677), 'created': datetime.datetime(2017, 6, 2, 7, 30, 6, 84658), 'uri': '/home/skaplun/.virtualenvs/labs3/var/data', 'name': 'default'}]
```

**Comment by jacquerie** [comment]
Turns out that `invenio-db` was quite broken, and [this commit](https://github.com/inveniosoftware/invenio-db/commit/502a2cc5e05f793a7bc3987e1eb938ca93f1d44a) fixes it.

Meanwhile we can do `inspirehep db drop --yes-i-know --verbose`...

**Comment by jacquerie** [comment]
That commit was released in https://github.com/inveniosoftware/invenio-db/commit/4df7ce16c2ae3f86f92596b1be4223f38604e543, so this issue can be closed.

**Comment by jacquerie** [comment]
CC: @jmartinm
