### ISSUE TITLE
Status not correctly reflected in ES Holding pen

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2485]
Currently there are 152 entries in the holding pen that are declared as running, when effectively their status should rather be ERROR or COMPLETED. The issue being that when the final JSON is sent to ES there is an exception:
```pythom
TransportError(400, u'mapper_parsing_exception', u'failed to parse [metadata.references.reference.authors]')
Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/invenio_workflows_ui/api.py", line 68, in wrapper
    self_or_cls.indexer.index(result)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_workflows_ui/indexer.py", line 66, in index
    body=self._prepare_record(record, index, doc_type),
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 279, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/transport.py", line 327, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 84, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/opt/inspire/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 114, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
RequestError: TransportError(400, u'mapper_parsing_exception', u'failed to parse [metadata.references.reference.authors]')
```

and therefore ES doesn't reflect the updated status and content.

**Comment by jmartinm** [comment]
Fixed
