### ISSUE TITLE
editor: "action_actionssystemroles does not exist" for routes require permission

### ISSUE THREAD

**Issue by harunurhan** [inspirehep/inspire-next#2671]
For the routes that we have `@editor_manage_tickets_permission` decorator, fails before calling the route function while trying to validate permission. It might be the same error for other permissions, I haven't checked.

## Expected Behavior

`403` or successful response if user has the permission

## Current Behavior

Fails with `500` and

```
17:16:37 web.1       | 127.0.0.1 - - [24/Aug/2017:17:16:37 +0200] "GET /api/editor/rt/queues HTTP/1.1" 500 56148 "http://localhost:4200/editor/literature/1497201" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/60.0.3112.101 Safari/537.36"
17:16:37 web.1       | Traceback (most recent call last):
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
17:16:37 web.1       |     return self.wsgi_app(environ, start_response)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/werkzeug/wsgi.py", line 660, in __call__
17:16:37 web.1       |     return app(environ, start_response)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
17:16:37 web.1       |     return self.wsgi_app(environ, start_response)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
17:16:37 web.1       |     response = self.handle_exception(e)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
17:16:37 web.1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
17:16:37 web.1       |     reraise(exc_type, exc_value, tb)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
17:16:37 web.1       |     response = self.full_dispatch_request()
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
17:16:37 web.1       |     rv = self.handle_user_exception(e)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
17:16:37 web.1       |     return cors_after_request(app.make_response(f(*args, **kwargs)))
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
17:16:37 web.1       |     reraise(exc_type, exc_value, tb)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
17:16:37 web.1       |     rv = self.dispatch_request()
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
17:16:37 web.1       |     return self.view_functions[rule.endpoint](**req.view_args)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_principal.py", line 198, in _decorated
17:16:37 web.1       |     with self:
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_principal.py", line 205, in __enter__
17:16:37 web.1       |     if not self.can():
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_principal.py", line 193, in can
17:16:37 web.1       |     return self.identity.can(self.permission)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_principal.py", line 152, in can
17:16:37 web.1       |     return permission.allows(self)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/flask_principal.py", line 333, in allows
17:16:37 web.1       |     if self.needs and not self.needs.intersection(identity.provides):
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/invenio_access/permissions.py", line 189, in needs
17:16:37 web.1       |     self._load_permissions()
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/invenio_access/permissions.py", line 163, in _load_permissions
17:16:37 web.1       |     explicit_need
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2654, in all
17:16:37 web.1       |     return list(self)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2802, in __iter__
17:16:37 web.1       |     return self._execute_and_instances(context)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 2817, in _execute_and_instances
17:16:37 web.1       |     result = conn.execute(querycontext.statement, self._params)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 914, in execute
17:16:37 web.1       |     return meth(self, multiparams, params)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 323, in _execute_on_connection
17:16:37 web.1       |     return connection._execute_clauseelement(self, multiparams, params)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1010, in _execute_clauseelement
17:16:37 web.1       |     compiled_sql, distilled_params
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1146, in _execute_context
17:16:37 web.1       |     context)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1341, in _handle_dbapi_exception
17:16:37 web.1       |     exc_info
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 203, in raise_from_cause
17:16:37 web.1       |     reraise(type(exception), exception, tb=exc_tb, cause=cause)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
17:16:37 web.1       |     context)
17:16:37 web.1       |   File "/Users/haurhan/.virtualenvs/inspirehep/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
17:16:37 web.1       |     cursor.execute(statement, parameters)
17:16:37 web.1       | ProgrammingError: (psycopg2.ProgrammingError) relation "access_actionssystemroles" does not exist
17:16:37 web.1       | LINE 2: FROM access_actionssystemroles
17:16:37 web.1       |              ^
17:16:37 web.1       |  [SQL: 'SELECT access_actionssystemroles.id AS access_actionssystemroles_id, access_actionssystemroles.action AS access_actionssystemroles_action, access_actionssystemroles.exclude AS access_actionssystemroles_exclude, access_actionssystemroles.argument AS access_actionssystemroles_argument, access_actionssystemroles.role_name AS access_actionssystemroles_role_name \nFROM access_actionssystemroles \nWHERE access_actionssystemroles.action = %(action_1)s AND access_actionssystemroles.argument IS NULL'] [parameters: {'action_1': 'editor_manage_tickets'}]
```

## Steps to Reproduce (for bugs)

1. run inspire-next (locally)
2. `GET /api/editor/rt/queues`

**Comment by harunurhan** [comment]
`recreate_records` fixed it

**Comment by jacquerie** [comment]
Yup, a `ProgrammingError` emitted from SQLAlchemy is typically caused by not having created the database, and a `docker-compose run --rm web scripts/recreate_records` should fix it.

I'm told @fschwenn and @ksachs experienced the same error when they tried installing LABS.
