### ISSUE TITLE
Wrongly generate journal.kb

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#2732]
## Current Behavior
reference task fails due to currently broken journal.kb:
```
Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/flask_celeryext/app.py", line 78, in __call__
    return Task.__call__(self, *args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_workflows/tasks.py", line 77, in start
    return text_type(run_worker(workflow_name, data, **kwargs).uuid)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_workflows/worker_engine.py", line 61, in run_worker
    engine.process(objects, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 390, in process
    self._process(objects)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 547, in _process
    obj, self, callbacks, exc_info
  File "/opt/inspire/lib/python2.7/site-packages/invenio_workflows/engine.py", line 364, in Exception
    obj, eng, callbacks, exc_info
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 970, in Exception
    reraise(*exc_info)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 529, in _process
    self.run_callbacks(callbacks, objects, obj)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 481, in run_callbacks
    self.execute_callback(callback_func, obj)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 564, in execute_callback
    callback(obj, self)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/utils.py", line 135, in _decorator
    res = func(*args, **kwargs)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/tasks/actions.py", line 253, in refextract
    references = extract_references(uri, source, {'journals': journal_kb_path})
  File "/opt/inspire/lib/python2.7/site-packages/timeout_decorator/timeout_decorator.py", line 81, in new_function
    return function(*args, **kwargs)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/tasks/refextract.py", line 94, in extract_references
    reference_format=u'{title},{volume},{page}'
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/api.py", line 145, in extract_references_from_file
    override_kbs_files=override_kbs_files,
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/engine.py", line 1421, in parse_references
    kbs = get_kbs(custom_kbs_files=override_kbs_files)
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/kbs.py", line 78, in get_kbs
    cache[cache_key] = load_kbs(kbs_files)
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/kbs.py", line 93, in load_kbs
    'journals': load_kb(kbs_files['journals'], build_journals_kb),
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/kbs.py", line 109, in load_kb
    return load_kb_from_file(path, builder)
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/kbs.py", line 537, in load_kb_from_file
    return builder(lazy_parser(fh))
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/kbs.py", line 578, in build_journals_kb
    for seek_phrase, repl in knowledgebase:
  File "/opt/inspire/lib/python2.7/site-packages/refextract/references/kbs.py", line 534, in lazy_parser
    % (path, rawline))
StandardError: Badly formatted kb '/eos/workspace/i/inspire/PROD/var/cache/journal-titles.kb' at line ---Rept.Prog.Phys.
```

Indeed the journal contains `/eos/workspace/i/inspire/PROD/var/cache/journal-titles.kb`
```
PROGR PHYS---Rept.Prog.Phys.
---Rept.Prog.Phys.
PEPORTSONPROGRESSINPHYSICS---Rept.Prog.Phys.
```

The KB should not be generated with wrong lines and refextract should not crash because of this.

**Comment by kaplun** [comment]
cc: @zzacharo

**Comment by kaplun** [comment]
The culprit is: https://inspirehep.net/record/1214416/export/xm

**Comment by zzacharo** [comment]
@kaplun this was modified by @jacquerie. SHould I check it or @jacquerie ?

**Comment by kaplun** [comment]
The code or the record?

**Comment by zzacharo** [comment]
the code that generates the `journal.kb`

**Comment by jacquerie** [comment]
Bad data:
```XML
<datafield tag="730" ind1=" " ind2=" ">
  <subfield code="a">+++++</subfield>
</datafield>
```
