### ISSUE TITLE
QA: pid already exists when accepting a harvested record

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#2910]
When accepting a record (https://qa.inspirehep.net/holdingpen/766164#errors) we are getting the following error:

```
Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 529, in _process
    self.run_callbacks(callbacks, objects, obj)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 465, in run_callbacks
    indent + 1)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 481, in run_callbacks
    self.execute_callback(callback_func, obj)
  File "/opt/inspire/lib/python2.7/site-packages/workflow/engine.py", line 564, in execute_callback
    callback(obj, self)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/utils/__init__.py", line 136, in _decorator
    res = func(*args, **kwargs)
  File "/opt/inspire/src/inspire/inspirehep/modules/workflows/tasks/upload.py", line 49, in store_record
    created_pid = inspire_recid_minter(str(record.id), record).pid_value
  File "/opt/inspire/src/inspire/inspirehep/modules/pidstore/minters.py", line 41, in inspire_recid_minter
    provider = InspireRecordIdProvider.create(**args)
  File "/opt/inspire/src/inspire/inspirehep/modules/pidstore/providers.py", line 78, in create
    object_type=object_type, object_uuid=object_uuid, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_pidstore/providers/base.py", line 68, in create
    status=status or cls.default_status,
  File "/opt/inspire/lib/python2.7/site-packages/invenio_pidstore/models.py", line 179, in create
    raise PIDAlreadyExists(pid_type=pid_type, pid_value=pid_value)
PIDAlreadyExists
```

**Comment by david-caro** [comment]
It turns out that the pidstore_recid table's sequence (pidstore_recid_recid_seq) was set to 1, so when getting the next available recid it got one that already existed, see this gist:

https://gist.github.com/david-caro/f73300176c774e7e2ae5618773511a30
