### ISSUE TITLE
PIDDoesNotExistError when retrieving for the first time all the records

### ISSUE THREAD

**Issue by chris-asl** [inspirehep/inspire-next#2980]
On my local installation with demo records containing only literature records, when retrieving all records (empty query) for the first time, I am getting `PIDDoesNotExistError`.

The error comes up, once the records are appearing in the frontend.

This is the related part of the logs:
```
13:08:18 web.1       | DEBUG in search_factory [/Users/chris/development/inspire/inspire-next/inspirehep/modules/search/search_factory.py:58]:
13:08:18 web.1       | {
13:08:18 web.1       |     "query": {
13:08:18 web.1       |         "bool": {
13:08:18 web.1       |             "filter": [
13:08:18 web.1       |                 {
13:08:18 web.1       |                     "bool": {
13:08:18 web.1       |                         "must_not": [
13:08:18 web.1       |                             {
13:08:18 web.1       |                                 "match": {
13:08:18 web.1       |                                     "_collections": "HERMES Internal Notes"
13:08:18 web.1       |                                 }
13:08:18 web.1       |                             }
13:08:18 web.1       |                         ],
13:08:18 web.1       |                         "must": [
13:08:18 web.1       |                             {
13:08:18 web.1       |                                 "match": {
13:08:18 web.1       |                                     "_collections": "literature"
13:08:18 web.1       |                                 }
13:08:18 web.1       |                             }
13:08:18 web.1       |                         ]
13:08:18 web.1       |                     }
13:08:18 web.1       |                 }
13:08:18 web.1       |             ],
13:08:18 web.1       |             "minimum_should_match": 1,
13:08:18 web.1       |             "must": [
13:08:18 web.1       |                 {
13:08:18 web.1       |                     "match_all": {}
13:08:18 web.1       |                 }
13:08:18 web.1       |             ]
13:08:18 web.1       |         }
13:08:18 web.1       |     },
13:08:18 web.1       |     "from": 0,
13:08:18 web.1       |     "size": 25
13:08:18 web.1       | }
13:08:18 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | ERROR in record_getter [/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py:59]:
13:08:20 web.1       | Can't load recid ('con', u'1510514')
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | Traceback (most recent call last):
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 57, in wrapper
13:08:20 web.1       |     return f(*args, **kwargs)
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 67, in get_es_record
13:08:20 web.1       |     pid = PersistentIdentifier.get(pid_type, recid)
13:08:20 web.1       |   File "/Users/chris/virtualenvs/inspire-next/lib/python2.7/site-packages/invenio_pidstore/models.py", line 212, in get
13:08:20 web.1       |     raise PIDDoesNotExistError(pid_type, pid_value)
13:08:20 web.1       | PIDDoesNotExistError
13:08:20 web.1       | /Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py:60: DeprecationWarning: BaseException.message has been deprecated as of Python 2.6
13:08:20 web.1       |   raise RecordGetterError(e.message, e)
13:08:20 web.1       |
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | ERROR in record_getter [/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py:59]:
13:08:20 web.1       | Can't load recid ('lit', u'1505802')
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | Traceback (most recent call last):
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 57, in wrapper
13:08:20 web.1       |     return f(*args, **kwargs)
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 67, in get_es_record
13:08:20 web.1       |     pid = PersistentIdentifier.get(pid_type, recid)
13:08:20 web.1       |   File "/Users/chris/virtualenvs/inspire-next/lib/python2.7/site-packages/invenio_pidstore/models.py", line 212, in get
13:08:20 web.1       |     raise PIDDoesNotExistError(pid_type, pid_value)
13:08:20 web.1       | PIDDoesNotExistError
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | ERROR in record_getter [/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py:59]:
13:08:20 web.1       | Can't load recid ('con', u'967841')
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | Traceback (most recent call last):
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 57, in wrapper
13:08:20 web.1       |     return f(*args, **kwargs)
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 67, in get_es_record
13:08:20 web.1       |     pid = PersistentIdentifier.get(pid_type, recid)
13:08:20 web.1       |   File "/Users/chris/virtualenvs/inspire-next/lib/python2.7/site-packages/invenio_pidstore/models.py", line 212, in get
13:08:20 web.1       |     raise PIDDoesNotExistError(pid_type, pid_value)
13:08:20 web.1       | PIDDoesNotExistError
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | ERROR in record_getter [/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py:59]:
13:08:20 web.1       | Can't load recid ('lit', u'347963')
13:08:20 web.1       | --------------------------------------------------------------------------------
13:08:20 web.1       | Traceback (most recent call last):
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 57, in wrapper
13:08:20 web.1       |     return f(*args, **kwargs)
13:08:20 web.1       |   File "/Users/chris/development/inspire/inspire-next/inspirehep/utils/record_getter.py", line 67, in get_es_record
13:08:20 web.1       |     pid = PersistentIdentifier.get(pid_type, recid)
13:08:20 web.1       |   File "/Users/chris/virtualenvs/inspire-next/lib/python2.7/site-packages/invenio_pidstore/models.py", line 212, in get
13:08:20 web.1       |     raise PIDDoesNotExistError(pid_type, pid_value)
13:08:20 web.1       | PIDDoesNotExistError
```

When visiting that page again I get no error.
But I can reproduce it after restarting the application.

_My guess is that this is something normal which happens since I only have `lit` records._

## Steps to Reproduce (for bugs)
1. Use the records provided below in the `recreate_records`  script.
2. Visit homepage, click on search button with empty query and see the logs.

## Context
[mele-muller-garcia_sciveres.xml.gz](https://github.com/inspirehep/inspire-next/files/1491252/mele-muller-garcia_sciveres.xml.gz)

**Comment by jmartinm** [comment]
This happens because a record has a `$ref` to a conference but the conference record itself is not loaded. The serializer tries to fetch the conference [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/serializers/json_literature.py#L62) and [here](https://github.com/inspirehep/inspire-next/blob/master/inspirehep/modules/records/wrappers.py#L65) in order to display some extra information like the title of the conference in the search results.

**Comment by chris-asl** [comment]
Makes sense! 
I think it's safe to close this one.
