### ISSUE TITLE
theme: don't hide original exception when the risen error has no `code`

### ISSUE THREAD

**Issue by david-caro** [inspirehep/inspire-next#3078]
When there's a non-flask exception risen on the app, the code that handles the returning value and code for those cases fails trying to access the `code` property of the exception and shadows the original one, for example:

```
[2017-12-20 17:52:13 +0000] [22518] [ERROR] Error handling request /api/institutions/?q=affautocomplete:Vrije%20U.%2C%20Amsterdam%2F%20*
Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/opt/inspire/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/inspire/lib/python2.7/site-packages/werkzeug/wsgi.py", line 669, in __call__
    return app(environ, start_response)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/opt/inspire/lib/python2.7/site-packages/raven/middleware.py", line 100, in __call__
    iterable = self.application(environ, start_response)
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/opt/inspire/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/opt/inspire/lib/python2.7/site-packages/flask/app.py", line 1547, in handle_exception
    return self.finalize_request(handler(e), from_error_handler=True)
  File "/opt/inspire/src/inspire/inspirehep/modules/theme/views.py", line 332, in wrapper
    six.reraise(*sys.exc_info())
  File "/opt/inspire/src/inspire/inspirehep/modules/theme/views.py", line 330, in wrapper
    return jsonify(code=error.code, message=error.name), error.code
AttributeError: 'exceptions.TypeError' object has no attribute 'code'
```

## Expected Behavior
I should properly handle non-flask exceptions too.

## Steps to Reproduce (for bugs)

1. See the above stack trace http request url.

**Comment by david-caro** [comment]
https://sentry.inspirehep.net/inspire-sentry/prod/issues/739/
