### ISSUE TITLE
Support multiple issn in journals

### ISSUE THREAD

**Issue by kaplun** [inspirehep/inspire-next#574]
Currently dojson fails e.g. on record https://inspirehep.net/record/1384337/export/xme because more than one issn is defined.
```python
09:47:50 worker.1  | Traceback (most recent call last):
09:47:50 worker.1  |   File "/home/skaplun/.virtualenvs/labs/src/inspire-next/inspire/modules/migrator/tasks.py", line 169, in create_record
09:47:50 worker.1  |     json = journals.do(record)
09:47:50 worker.1  |   File "/home/skaplun/.virtualenvs/labs/local/lib/python2.7/site-packages/dojson/overdo.py", line 73, in do
09:47:50 worker.1  |     output[name] = creator(output, key, value)
09:47:50 worker.1  |   File "/home/skaplun/.virtualenvs/labs/src/inspire-next/inspire/dojson/journals/fields/bd1xx.py", line 33, in issn
09:47:50 worker.1  |     return value.get("a")
09:47:50 worker.1  | AttributeError: 'list' object has no attribute 'get'
```

* [ ] dojson for journal records to support multiple issn and corresponding qualifiers in `$b`
* [ ] JSONSchema to reflect this
* [ ] elasticsearch mapping to reflect this
* [ ] format to reflect this

cc @jmartinm, @ioannistsanaktsidis

**Comment by ioannistsanaktsidis** [comment]
Also this one you can assign to me. I will take are.
