### ISSUE TITLE
query-parser: exception on malformed query

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#763]
If you make a malformed query with e.g. an unbalanced parenthesis the following error happens:

Query: ``mmbmbmn (``

```traceback
Traceback (most recent call last):
  File "/Users/jlavik/Envs/next/src/invenio-search/invenio_search/views/search.py", line 205, in search
    response = Query(p).search(collection=collection.name)
  File "/Users/jlavik/Envs/next/src/invenio-search/invenio_search/api.py", line 66, in search
    query = self.query
  File "/Users/jlavik/Envs/next/lib/python2.7/site-packages/werkzeug/utils.py", line 71, in __get__
    value = self.func(obj)
  File "/Users/jlavik/Envs/next/src/invenio-search/invenio_search/api.py", line 57, in query
    tree = pypeg2.parse(self._query, parser(), whitespace="")
  File "/Users/jlavik/Envs/next/lib/python2.7/site-packages/pypeg2/__init__.py", line 669, in parse
    raise parser.last_error
SyntaxError: expecting one of [<class 'invenio_query_parser.parser.AndQuery'>, <class 'invenio_query_parser.parser.OrQuery'>, <class 'invenio_query_parser.parser.ImplicitAndQuery'>] (line 1)
```

This should be caught more nicely and may be transformed into value query or abort query, either way it should return to the search results page with a message to the user that there was something wrong with the query but here are the results after doing a fallback search (or something).

@kaplun @jmartinm @Panos512

**Comment by kaplun** [comment]
:+1: @Panos512 this can be done in the similar way as the trick of the Google like search
