### ISSUE TITLE
receivers: match_valid_experiments problem

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#792]
```shell
In [3]: from inspirehep.modules.records.receivers import match_valid_experiments

In [4]: match_valid_experiments('1', {u'accelerator_experiments': [{u'curated_relation': False, u'experiment': [u'MAGIC', u'MAGIC']}]})
```

```traceback
Traceback (most recent call last):
  File "/opt/inspire/lib/python2.7/site-packages/celery/app/trace.py", line 240, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/inspire/lib/python2.7/site-packages/invenio_records/tasks/index.py", line 47, in index_record
    before_record_index.send(recid, json=json, index=index)
  File "/opt/inspire/lib/python2.7/site-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/opt/inspire/src/inspire/inspirehep/modules/records/receivers.py", line 95, in match_valid_experiments
    experiment = experiment.lower()
AttributeError: 'list' object has no attribute 'lower'
```

The receiver should be updated to handle the case where `experiment` key is a list.

**Comment by Panos512** [comment]
I am working on it
