### ISSUE TITLE
Conversion errors in Record migration

### ISSUE THREAD

**Issue by jalavik** [inspirehep/inspire-next#987]
**NOTE that some codepaths will be different on Invenio 3 version of INSPIRE.**

Doing a full load of INSPIRE into QA revealed still a few record errors:

```
Traceback (most recent call last):
 File "/opt/inspire/src/inspire/inspirehep/modules/migrator/tasks.py", line 245, in migrate_chunk
 dry_run=dry_run, validation=True
 File "/opt/inspire/src/inspire/inspirehep/modules/migrator/tasks.py", line 398, in create_record
 json = strip_empty_values(hep.do(record))
 File "/opt/inspire/src/inspire/inspirehep/dojson/hep/model.py", line 51, in do
 add_book_info(output, blob)
 File "/opt/inspire/src/inspire/inspirehep/dojson/hep/model.py", line 37, in add_book_info
 collections.append(c.get('primary').lower())
AttributeError: 'tuple' object has no attribute 'lower'

ERROR with record 775757 and json None
```

```
[2016-03-10 02:33:54,869: ERROR/Worker-11] inspirehep.modules.migrator.tasks.migrate_chunk[e9d44d89-67fe-4760-afc9-ac2a8b91b929]: ERROR with record 887476 and json {'oai_pmh': [{'set': (u'INSPIRE:HEP', u'CDS'), 'id': u'oai:inspirehep.net:887476'}], 'date_and_time_of_latest_transaction': u'20140307211849.0', 'report_numbers': [{'value': u'BONN-IB-96-34'}], '_collections': [u'HEP'], 'control_number': u'887476', 'subject_terms': [{'term': u'Instrumentation', 'scheme': u'INSPIRE'}], 'external_system_numbers': [{'institute': u'INSPIRETeX', 'obsolete': False, 'value': u'Voss:1975sva'}, {'institute': u'CDS', 'obsolete': False, 'value': u'553209'}], 'title_translation': [{'title': u'Proof of electrons in a magnetic spectrometer'}], 'languages': [u'German'], 'authors': [{'profile': {'__url__': u'http://inspirehep.net/record/984423'}, 'uuid': '76d4f827-8181-4858-99d8-7d31b440c1f1', 'curated_relation': False, 'affiliations': [{'value': u'Munich U.'}], 'recid': 984423, 'full_name': u'Voss, R\xfcdiger', 'signature_block': u'Vr'}], 'titles': [{'title': u'Nachweis von Elektronen in einem Magnetspektrometer'}], 'collections': [{'primary': u'Thesis'}, {'primary': u'CORE'}, {'primary': u'HEP'}], 'creation_modification_date': [{'modification_date': u'2011-02-08', 'creation_date': u'2014-03-07'}], 'thesis': [{'date': u'1975', 'curated_relation': False, 'university': u'Munich U.', 'degree_type': u'Master'}], 'accelerator_experiments': [{'curated_relation': False, 'experiment': (u'AMS', u'PAMELA', u'ISOMAX')}], 'breadcrumb_title': u'Nachweis von Elektronen in einem Magnetspektrometer', 'dois': [], 'facet_inspire_subjects': [u'Instrumentation'], 'earliest_date': '1975'}


[2016-03-10 02:33:55,027: ERROR/Worker-11] inspirehep.modules.migrator.tasks.migrate_chunk[e9d44d89-67fe-4760-afc9-ac2a8b91b929]: 'tuple' object has no attribute 'lower'
Traceback (most recent call last):
 File "/opt/inspire/src/inspire/inspirehep/modules/migrator/tasks.py", line 253, in migrate_chunk
 before_record_index.send(recid, json=json, index=index)
 File "/opt/inspire/lib/python2.7/site-packages/blinker/base.py", line 267, in send
 for receiver in self.receivers_for(sender)]
 File "/opt/inspire/src/inspire/inspirehep/modules/records/receivers.py", line 136, in match_valid_experiments
 experiment = experiment.lower()
AttributeError: 'tuple' object has no attribute 'lower'
```

```
[2016-03-10 02:48:52,239: ERROR/Worker-10] inspirehep.modules.migrator.tasks.migrate_chunk[c6b11eee-1f07-4758-83da-018f12aa2a34]: 'NoneType' object is not iterable
Traceback (most recent call last):
 File "/opt/inspire/src/inspire/inspirehep/modules/migrator/tasks.py", line 245, in migrate_chunk
 dry_run=dry_run, validation=True
 File "/opt/inspire/src/inspire/inspirehep/modules/migrator/tasks.py", line 385, in create_record
 json = strip_empty_values(institutions.do(record))
 File "/opt/inspire/src/inspire/inspirehep/dojson/schema.py", line 32, in do
 output = super(SchemaOverdo, self).do(blob, **kwargs)
 File "/opt/inspire/lib/python2.7/site-packages/dojson/overdo.py", line 125, in do
 data = creator(output, key, value)
 File "/opt/inspire/lib/python2.7/site-packages/dojson/utils.py", line 55, in wrapper
 return [f(self, key, values, **kwargs)]
 File "/opt/inspire/src/inspire/inspirehep/dojson/institutions/fields/bd1xx.py", line 77, in name
 names = list(utils.force_list(value.get('a'))) or []
TypeError: 'NoneType' object is not iterable

ERROR with record 902715 and json None
```

More incoming..

**Comment by jalavik** [comment]
Outdated
